-- Create questions table
CREATE TABLE IF NOT EXISTS public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  topic TEXT,
  author_name TEXT, -- Optional, if we want to display who asked
  likes INTEGER DEFAULT 0,
  replies INTEGER DEFAULT 0
);

-- Enable RLS
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Allow public read/write for now to ensure it works without complex auth first
CREATE POLICY "Allow public select" ON public.questions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert" ON public.questions FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.questions FOR UPDATE TO anon, authenticated USING (true);
