-- Run this in your Supabase SQL Editor to enable Custom Auth

-- 1. Create or Update Table
CREATE TABLE IF NOT EXISTS public.login (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
--   uuid UUID NOT NULL REFERENCES auth.users(id), -- No longer strictly needed for custom auth, but good to keep if mixing
  name TEXT,
  email TEXT,
  password TEXT -- Storing password directly as requested
);

-- 2. Enable RLS
ALTER TABLE public.login ENABLE ROW LEVEL SECURITY;

-- 3. DROP old policies to avoid conflicts
DROP POLICY IF EXISTS "Allow authenticated users to insert their own profile" ON public.login;
DROP POLICY IF EXISTS "Allow users to read their own profile" ON public.login;
DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.login;
DROP POLICY IF EXISTS "Allow anon insert" ON public.login;
DROP POLICY IF EXISTS "Allow public read" ON public.login;

-- 4. Create New Policies for Custom Auth

-- Allow ANYONE (anon) to insert (Register)
CREATE POLICY "Allow anon insert" 
ON public.login 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Allow ANYONE (anon) to select (Login)
-- We need this so the Login page can search for email/password match
CREATE POLICY "Allow public read" 
ON public.login 
FOR SELECT 
TO anon, authenticated 
USING (true);

-- Allow users to update (this is trickier without auth.uid(), usually handled by logic)
-- For now, basic update policy (might need refinement based on exact reqs)
CREATE POLICY "Allow public update" 
ON public.login 
FOR UPDATE 
TO anon, authenticated 
USING (true);
